version: "2"
services:
  rds_dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    image: node:24-alpine
    container_name: rds_dashboard
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 8085:5173
